### ISSUE TITLE
Уже пора делать на базах данных

### ISSUE THREAD

**Issue by coursar** [evgeniychernyshev/seller-workplace#2]
https://github.com/evgeniychernyshev/seller-workplace/blob/a44763bcc3bb41af23847858aa561849ef44d3a2/app/GoodManager.py#L3

Обратите внимание, что этот код небезопасен - мы его рассматривали только в демонстрационных целях

**Comment by evgeniychernyshev** [comment]
Напомните пожалуйста, почему небезопасен и как правильно?

**Comment by coursar** [comment]
Потому что в production среде вы будете это запускать по gunicorn или waitress и много процессов вашего приложения будет запускаться одновременно

Надо через базу данных
